### ISSUE TITLE
Publish as nuGet-Package

### ISSUE THREAD

**Issue by gbrueckl** [gbrueckl/Azure.DataFactory.LocalEnvironment#1]
Publish the DLL as nuGet-Package for easier deployment

**Comment by m1nkeh** [comment]
this would be amazing @gbrueckl if it could get done, we use this repo on a lot of projects and to have it as a pkg that is super easy to install would be very much appreciated!

**Comment by gbrueckl** [comment]
will publish it within this week - stay tuned!

**Comment by gbrueckl** [comment]
@m1nkeh just published the NuGet package and updated the documentation
https://www.nuget.org/packages/gbrueckl.Azure.DataFactory.LocalEnvironment

**Comment by m1nkeh** [comment]
@gbrueckl exceptional, many thanks!
