### ISSUE TITLE
VS Test Debugging Issue with debuggerBuildPath

### ISSUE THREAD

**Issue by nigelmeakins** [gbrueckl/Azure.DataFactory.LocalEnvironment#12]
When executing with VS Test, debugging fails due to the AppDomain.CurrentDomain.BaseDirectory being slightly different. 
Change the following:
ADFLocalEnvironment.cs : Line 329:

`debuggerBuildPath = string.Join("\\", AppDomain.CurrentDomain.BaseDirectory.GetTokens('\\', 0, AppDomain.CurrentDomain.BaseDirectory.EndsWith("\\") ? 3 : 2, true));`

This then returns the correct path when stepping in via VS Test.

**Comment by gbrueckl** [comment]
thanks for the feedback. I just did the change as you suggested!
for the future, please use Pull-Requests to suggest these kinds of changes. This makes it easier for me to merge the changes and you also get listed as contributor to the project

**Comment by nigelmeakins** [comment]
Hi Gerhard,

Thanks for your reply. I did try and create a pull request but unfortunately was getting an access denied response. I may have been doing something wrong my end however.

Regards

Nigel

________________________________
