### ISSUE TITLE
Consider less restrictive license

### ISSUE THREAD

**Issue by drorkremer** [gbrueckl/Azure.DataFactory.LocalEnvironment#3]
Is the choice of GPLv3 intentional?
This license is too restrictive for consuming in some corporate environments (such as Microsoft).
A less restrictive license such as MIT License, Microsoft Public License or Apache License 2.0 will considerably simplify legal implications associated with GPLv3 and enable using this project (especially it only exists in source form and a nuget package is not yet available).

**Comment by gbrueckl** [comment]
Changed to MIT license
