### ISSUE TITLE
UnauthorizedAccessException when deleting dependencies

### ISSUE THREAD

**Issue by ollief87** [gbrueckl/Azure.DataFactory.LocalEnvironment#5]
Receiving UnauthorizedAccessException on line 510 of ADFLocalEnvironment.cs when attempting to delete dependencies after executing the .NET activity
![delete failing](https://cloud.githubusercontent.com/assets/7812769/23393678/a1637b02-fdd8-11e6-90f4-09d29e72af1a.png)
Putting a break point on the delete and attempting to delete the files manually from Windows shows that they are in use
![file in use](https://cloud.githubusercontent.com/assets/7812769/23393711/e435e33e-fdd8-11e6-9c0c-4a97803a6aa5.png)

**Comment by gbrueckl** [comment]
I just deployed a quick fix where I delete the temporary folder before extracting the ZIP file. This way I can at least ensure no old files reside in the folder.
deleting the folder after the debugging is a bit more tricky ad the DLL is loaded into the same AppDomain as the current code and so the file is locked until the caller finishes
I played around with different AppDomains but gave up as i could not find a working solution yet

to deal with the actual error, I simply wrapped a try/catch block around it

**Comment by ollief87** [comment]
Yeah I've done the same for now, just catching UnauthorizedAccessException. I also found if I tried to call another activity straight afterwards it throws a IOException because the files already exist and are in use

**Comment by gbrueckl** [comment]
in case we want to execute multiple activities in the same run we would also need to wrap the initial deletion of the folder in a try/catch block.
I will consider this for a future feature

**Comment by gbrueckl** [comment]
fixed with latest release
cleanup is now done at start and can also deal with multiple executions in the same run
