### ISSUE TITLE
Cannot reference the dll

### ISSUE THREAD

**Issue by tomasfalt** [gbrueckl/Azure.DataFactory.LocalEnvironment#8]
I downloaded the dll in [Azure.DataFactory.LocalEnvironment/ADFLocalEnvironment/Download/gbrueckl.Azure.DataFactory.ADFLocalEnvironment.dll](https://github.com/gbrueckl/Azure.DataFactory.LocalEnvironment/blob/master/ADFLocalEnvironment/Download/gbrueckl.Azure.DataFactory.ADFLocalEnvironment.dll) 

But when I try to reference it from VS 2015 I get "A reference to the dll could not be added". 

I also tried regsvr32 and dependency walker but both told me that is something wrong with the dll.

**Comment by gbrueckl** [comment]
have you tried adding the DLL via its absolute path?
are yo using a classic C# project and not a C# Core project?

**Comment by tomasfalt** [comment]
Sorry my bad. Now it's working. Thank you for a really nice solution which will probably help me a lot!
